"use client";
import { useEffect, useState } from "react";
import type { ContentEntry, ContentKind, ContentImage } from "@/types/cms";
import { starterPosts } from "@/data/posts";
import { starterPuppies } from "@/data/starter-puppies";
import { initialAwards } from "@/data/live-awards";
const labels: Record<ContentKind,string> = {puppy:"Yavrular",post:"Blog",story:"Yeni yuvalarında",award:"Ödüller"};
type Draft = Omit<ContentEntry,"id"|"updated_at"> & {id?:string;updated_at?:string};
function blank(kind: ContentKind): Draft { return {kind,slug:"",published:false,sort_index:0,payload:{title:"",description:"",body:"",images:[],breed:"Toy Poodle",status:"available",sex:"Dişi",traits:[]}}; }
export function AdminPanel({configured}:{configured:boolean}) {
  const [authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(configured),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [records,setRecords]=useState<ContentEntry[]>([]),[kind,setKind]=useState<ContentKind>("puppy"),[draft,setDraft]=useState<Draft>(blank("puppy")),[dirty,setDirty]=useState(false);
  async function api(action:string,data?:unknown,raw?:File) { const res=await fetch(`/api/admin/${action}/`,data || raw ? {method:"POST",headers:{"Content-Type":raw?"application/octet-stream":"application/json"},body:raw || JSON.stringify(data)}:{});const body=await res.json();if(!res.ok){if(res.status===401)setAuthenticated(false);throw Error(body.error || "İşlem tamamlanamadı.");}return body; }
  async function refresh(){const data=await api("content");setRecords(data);setAuthenticated(true);return data as ContentEntry[];}
  useEffect(()=>{if(!configured)return;fetch("/api/admin/content/").then(async r=>{if(r.ok){setRecords(await r.json());setAuthenticated(true);}}).catch(()=>setMessage("Sunucuya bağlanılamadı.")).finally(()=>setLoading(false));},[configured]);
  useEffect(()=>{function warn(e:BeforeUnloadEvent){if(dirty){e.preventDefault();}}window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  function choose(next:Draft){if(dirty&&!confirm("Kaydedilmemiş değişiklikler var. Vazgeçilsin mi?"))return;setDraft(structuredClone(next));setKind(next.kind);setDirty(false);setMessage("");}
  function payload(key:string,value:unknown){setDraft(d=>({...d,payload:{...d.payload,[key]:value}}));setDirty(true);}
  function images(next:ContentImage[]){payload("images",next);}
  if(!configured)return <section className="shell admin-area"><p className="eyebrow">LUMO YÖNETİM</p><h1>Güvenli bağlantı kurulmalı.</h1><p>Supabase bağlantısı henüz tanımlanmamış. Yönetim paneli bağlantı tamamlanana kadar kapalıdır.</p><p>Kurulum adımları proje içindeki ADMIN_KURULUM.md dosyasındadır.</p></section>;
  if(loading)return <section className="shell admin-area"><p>Oturum kontrol ediliyor…</p></section>;
  if(!authenticated)return <section className="shell admin-area admin-login"><p className="eyebrow">LUMO YÖNETİM</p><h1>Hoş geldiniz.</h1><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage("");const data=new FormData(e.currentTarget);try{await api("login",Object.fromEntries(data));await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label>E-posta<input name="email" type="email" required autoComplete="username" /></label><label>Şifre<input name="password" type="password" required autoComplete="current-password" /></label><button className="button" disabled={busy}>{busy?"Giriş yapılıyor…":"Giriş yap"}</button><p role="status">{message}</p></form></section>;
  return <section className="shell admin-area"><header className="admin-top"><div><p className="eyebrow">LUMO YÖNETİM</p><h1>İçeriklerinizi yönetin.</h1></div><button disabled={busy} onClick={async()=>{if(dirty&&!confirm("Değişiklikler kaydedilmedi. Çıkış yapılsın mı?"))return;try{await api("logout",{});setAuthenticated(false);setDirty(false);}catch(e){setMessage((e as Error).message);}}}>Çıkış yap</button></header>
    <nav className="admin-tabs" aria-label="İçerik türü">{Object.entries(labels).map(([key,label])=><button disabled={busy} aria-pressed={kind===key} key={key} onClick={()=>choose(blank(key as ContentKind))}>{label}</button>)}</nav>
    <p role="status" className="admin-message">{message}</p><div className="admin-layout"><aside><button className="button" disabled={busy} onClick={()=>choose(blank(kind))}>Yeni kayıt ekle</button><button disabled={busy} onClick={async()=>{if(dirty&&!confirm("Kaydedilmemiş değişiklikler kaybolacak. Yenilensin mi?"))return;try{const rows=await refresh();choose(rows.find(r=>r.id===draft.id)||blank(kind));}catch(e){setMessage((e as Error).message);}}}>Listeyi yenile</button>
    {records.filter(r=>r.kind===kind).map(r=><button className="admin-record" disabled={busy} key={r.id} aria-pressed={r.id===draft.id} onClick={()=>choose(r)}>{r.payload.images[0]&&<img src={r.payload.images[0].src} alt="" />}<span>{r.payload.title}<small>{r.published?"Yayında":"Taslak"}</small></span></button>)}
    {(kind==="post"||kind==="award"||kind==="puppy")&&!records.some(r=>r.kind===kind)&&<button disabled={busy} onClick={async()=>{setBusy(true);try{for(const p of kind==="post"?starterPosts:kind==="puppy"?starterPuppies:initialAwards){await api("save",{...p,id:undefined,updated_at:undefined});}await refresh();setMessage("Başlangıç içerikleri eklendi.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{kind==="post"?"3 başlangıç yazısını ekle":kind==="puppy"?"4 örnek yavruyu ekle":"Ödül kaydını ekle"}</button>}</aside>
    <form className="admin-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage("");try{const saved=await api("save",draft);setDraft(saved);setDirty(false);await refresh();setMessage(saved.published?"Kaydedildi. Yayındaki içerik güncellendi.":"Taslak kaydedildi. Sitede görünmüyor.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>
    <fieldset disabled={busy}><legend>{draft.id?"Kaydı düzenle":"Yeni kayıt"} {dirty?"· Kaydedilmedi":""}</legend><label>Başlık / isim<input required maxLength={140} value={draft.payload.title} onChange={e=>{const value=e.target.value;setDraft(d=>({...d,payload:{...d.payload,title:value},...(!d.id?{slug:value.toLocaleLowerCase("tr").replace(/ı/g,"i").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}:{})}));setDirty(true);}} /></label>
    <div className="admin-two"><label>Bağlantı adı<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={draft.slug} onChange={e=>{setDraft({...draft,slug:e.target.value});setDirty(true);}} /></label><label>Sıralama<input type="number" min={0} max={9999} value={draft.sort_index} onChange={e=>{setDraft({...draft,sort_index:Number(e.target.value)});setDirty(true);}} /></label></div>
    {kind==="puppy"&&<><label className="admin-checkbox"><input type="checkbox" checked={draft.payload.featured===true} onChange={e=>payload("featured",e.target.checked)} /> Ana sayfada öne çıkar</label><p>Yayımlanmış ve yuvasını bulmamış kayıtlardan, sıralama numarası en küçük ilk 4 yavru gösterilir.</p><div className="admin-two"><label>Irk<select value={draft.payload.breed} onChange={e=>payload("breed",e.target.value)}>{["Toy Poodle","Pomeranian","Maltipoo","Poodle melezi"].map(b=><option key={b}>{b}</option>)}</select></label><label>Cinsiyet<select value={draft.payload.sex} onChange={e=>payload("sex",e.target.value)}><option>Dişi</option><option>Erkek</option></select></label><label>Renk<input value={draft.payload.colour||""} onChange={e=>payload("colour",e.target.value)} /></label><label>Doğum tarihi<input type="date" value={draft.payload.birthDate||""} onChange={e=>payload("birthDate",e.target.value)} /></label><label>Durum<select value={draft.payload.status} onChange={e=>payload("status",e.target.value)}><option value="available">Tanışmaya açık</option><option value="reserved">Rezerve</option><option value="home">Yuvasını buldu</option></select></label><label>Özellikler · virgülle ayırın<input value={(draft.payload.traits||[]).join(",")} onChange={e=>payload("traits",e.target.value.split(","))} /></label></div></>}
    {kind==="post"&&<label>Kategori<input value={draft.payload.category||""} onChange={e=>payload("category",e.target.value)} /></label>}
    {kind==="award"&&<div className="admin-two"><label>Etkinlik / organizasyon<input value={draft.payload.event||""} onChange={e=>payload("event",e.target.value)} /></label><label>Yıl<input pattern="[0-9]{4}" value={draft.payload.year||""} onChange={e=>payload("year",e.target.value)} /></label></div>}
    <label>Kısa açıklama<textarea maxLength={400} rows={3} value={draft.payload.description} onChange={e=>payload("description",e.target.value)} /></label><label>{kind==="post"?"Yazı metni · başlıkları ## ile başlatın":"Ayrıntılar"}<textarea rows={12} value={draft.payload.body} onChange={e=>payload("body",e.target.value)} /></label>
    <label>Görsel ekle · JPG, PNG, WebP / en fazla 5 MB<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value="";if(files.length+draft.payload.images.length>12){setMessage("En fazla 12 görsel ekleyin.");return;}setBusy(true);try{const added=[...draft.payload.images];for(const file of files){if(file.size>5242880)throw Error("Her görsel en fazla 5 MB olabilir.");const image=await api("upload",undefined,file);added.push({...image,alt:draft.payload.title});images([...added]);}setMessage("Görseller yüklendi. Değişiklikleri kaydedin.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}} /></label>
    <div className="admin-images">{draft.payload.images.map((image,index)=><div key={image.src}><img src={image.src} alt={image.alt} /><label>Görsel açıklaması<input value={image.alt} onChange={e=>images(draft.payload.images.map((im,i)=>i===index?{...im,alt:e.target.value}:im))} /></label><button type="button" disabled={index===0} onClick={()=>{const next=[...draft.payload.images];[next[index-1],next[index]]=[next[index],next[index-1]];images(next);}}>Öne al</button><button type="button" onClick={()=>images(draft.payload.images.filter((_,i)=>i!==index))}>Kaldır</button><small>{index===0?"Kapak görseli":"Galeri"}</small></div>)}</div>
    <label className="admin-checkbox"><input type="checkbox" checked={draft.published} onChange={e=>{setDraft({...draft,published:e.target.checked});setDirty(true);}} /> Sitede yayımla</label><p>Yuva hikâyelerinde ve fotoğraflarda paylaşım izni alınmış içerikleri kullanın.</p><div className="admin-actions"><button className="button" type="submit">{busy?"Kaydediliyor…":"Değişiklikleri kaydet"}</button>{draft.id&&<button type="button" onClick={async()=>{if(!confirm("Bu kayıt kalıcı olarak silinsin mi?"))return;setBusy(true);try{await api("delete",{id:draft.id,updated_at:draft.updated_at});setDraft(blank(kind));setDirty(false);await refresh();setMessage("Kayıt silindi.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Kaydı sil</button>}</div></fieldset></form></div></section>;
}
